---
version: '3.8'

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: controlpanel
      POSTGRES_PASSWORD: controlpanel
      POSTGRES_DB: controlpanel
    ports:
      - "5432:5432"
