services:
  db:
    extends:
      file: docker-compose-postgres.yml
      service: postgres

  interfaces:
    image: ${IMAGE_TAG}
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
    links: [db]
    environment:
      ALLOWED_HOSTS: "localhost 127.0.0.1 0.0.0.0"
      DB_HOST: "db"
      DB_NAME: controlpanel
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_USER: controlpanel
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "controlpanel.settings.test"
      ENV: "dev"
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_OP_CONF_URL: ${OIDC_OP_CONF_URL}
      PYTHONUNBUFFERED: "1"
      SECRET_KEY: "1234567890"
      ENABLE_DB_SSL: "False"
