# Generated by Django 4.2.7 on 2024-02-28 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("name",)},
        ),
    ]
